<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261009185119 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE grille_tarifaire (id_tarif INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_debut DATE NOT NULL, date_fin DATE DEFAULT NULL, couleur VARCHAR(50) NOT NULL, deb TIME(0) WITHOUT TIME ZONE DEFAULT NULL, fin TIME(0) WITHOUT TIME ZONE DEFAULT NULL, tarif NUMERIC(10, 4) DEFAULT NULL, type VARCHAR(10) NOT NULL, puissance INT DEFAULT NULL, PRIMARY KEY (id_tarif))');
        $this->addSql('CREATE TABLE import (id_import INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_fichier VARCHAR(255) NOT NULL, date_import TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_debut_donnees DATE DEFAULT NULL, date_fin_donnees DATE DEFAULT NULL, statut VARCHAR(255) NOT NULL, PRIMARY KEY (id_import))');
        $this->addSql('CREATE TABLE jour (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_jour DATE NOT NULL, couleur VARCHAR(50) NOT NULL, production_energie_hc NUMERIC(15, 3) DEFAULT NULL, production_energie_hp NUMERIC(15, 3) DEFAULT NULL, production_puissance_max NUMERIC(10, 2) DEFAULT NULL, production_heure_puissance_max TIME(0) WITHOUT TIME ZONE DEFAULT NULL, energie_importee_hc NUMERIC(15, 3) DEFAULT NULL, energie_importee_hp NUMERIC(15, 3) DEFAULT NULL, soc_min NUMERIC(5, 2) DEFAULT NULL, soc_max NUMERIC(5, 2) DEFAULT NULL, soh NUMERIC(5, 2) DEFAULT NULL, temperature_min NUMERIC(5, 2) DEFAULT NULL, temperature_max NUMERIC(5, 2) DEFAULT NULL, nb_alarmes INT DEFAULT NULL, ve_energie_hc NUMERIC(15, 3) DEFAULT NULL, ve_energie_hp NUMERIC(15, 3) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE statistique_globale (annee INT NOT NULL, energie_totale_produite NUMERIC(15, 3) DEFAULT NULL, energie_totale_importee NUMERIC(15, 3) DEFAULT NULL, energie_totale_ve NUMERIC(15, 3) DEFAULT NULL, soc_max_observe NUMERIC(5, 2) DEFAULT NULL, soh_min_observe NUMERIC(5, 2) DEFAULT NULL, puissance_max_production NUMERIC(10, 2) DEFAULT NULL, PRIMARY KEY (annee))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE grille_tarifaire');
        $this->addSql('DROP TABLE import');
        $this->addSql('DROP TABLE jour');
        $this->addSql('DROP TABLE statistique_globale');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
