<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260902091734 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE batterie_jour (soc_moyen NUMERIC(5, 2) DEFAULT NULL, soc_min NUMERIC(5, 2) DEFAULT NULL, soc_max NUMERIC(5, 2) DEFAULT NULL, soh NUMERIC(5, 2) DEFAULT NULL, temperature_min NUMERIC(5, 2) DEFAULT NULL, temperature_max NUMERIC(5, 2) DEFAULT NULL, nb_alarmes INT DEFAULT NULL, date_jour DATE NOT NULL, PRIMARY KEY (date_jour))');
        $this->addSql('CREATE TABLE consommation_jour (energie_importee_hc NUMERIC(15, 3) DEFAULT NULL, energie_importee_hp NUMERIC(15, 3) DEFAULT NULL, date_jour DATE NOT NULL, PRIMARY KEY (date_jour))');
        $this->addSql('CREATE TABLE grille_tarifaire (id_tarif INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_debut DATE NOT NULL, date_fin DATE DEFAULT NULL, couleur VARCHAR(50) NOT NULL, deb_hc TIME(0) WITHOUT TIME ZONE DEFAULT NULL, tarif_hc NUMERIC(10, 4) DEFAULT NULL, deb_hp TIME(0) WITHOUT TIME ZONE DEFAULT NULL, tarif_hp NUMERIC(10, 4) DEFAULT NULL, PRIMARY KEY (id_tarif))');
        $this->addSql('CREATE TABLE import (id_import INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_fichier VARCHAR(255) NOT NULL, date_import TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_debut_donnees DATE DEFAULT NULL, date_fin_donnees DATE DEFAULT NULL, PRIMARY KEY (id_import))');
        $this->addSql('CREATE TABLE jour (date_jour DATE NOT NULL, couleur VARCHAR(50) NOT NULL, PRIMARY KEY (date_jour))');
        $this->addSql('CREATE TABLE production_jour (energie_hc NUMERIC(15, 3) DEFAULT NULL, energie_hp NUMERIC(15, 3) DEFAULT NULL, puissance_max NUMERIC(10, 2) DEFAULT NULL, heure_puissance_max TIME(0) WITHOUT TIME ZONE DEFAULT NULL, date_jour DATE NOT NULL, PRIMARY KEY (date_jour))');
        $this->addSql('CREATE TABLE statistique_globale (annee INT NOT NULL, energie_totale_produite NUMERIC(15, 3) DEFAULT NULL, energie_totale_importee NUMERIC(15, 3) DEFAULT NULL, energie_totale_ve NUMERIC(15, 3) DEFAULT NULL, soc_max_observe NUMERIC(5, 2) DEFAULT NULL, soh_min_observe NUMERIC(5, 2) DEFAULT NULL, puissance_max_production NUMERIC(10, 2) DEFAULT NULL, PRIMARY KEY (annee))');
        $this->addSql('CREATE TABLE ve_jour (energie_hc NUMERIC(15, 3) DEFAULT NULL, energie_hp NUMERIC(15, 3) DEFAULT NULL, duree_charge_minutes INT DEFAULT NULL, date_jour DATE NOT NULL, PRIMARY KEY (date_jour))');
        $this->addSql('ALTER TABLE batterie_jour ADD CONSTRAINT FK_9CF39679FAC95031 FOREIGN KEY (date_jour) REFERENCES jour (date_jour) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE consommation_jour ADD CONSTRAINT FK_31982FD2FAC95031 FOREIGN KEY (date_jour) REFERENCES jour (date_jour) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE production_jour ADD CONSTRAINT FK_10792D1FAC95031 FOREIGN KEY (date_jour) REFERENCES jour (date_jour) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ve_jour ADD CONSTRAINT FK_BFDFA45FAC95031 FOREIGN KEY (date_jour) REFERENCES jour (date_jour) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE batterie_jour DROP CONSTRAINT FK_9CF39679FAC95031');
        $this->addSql('ALTER TABLE consommation_jour DROP CONSTRAINT FK_31982FD2FAC95031');
        $this->addSql('ALTER TABLE production_jour DROP CONSTRAINT FK_10792D1FAC95031');
        $this->addSql('ALTER TABLE ve_jour DROP CONSTRAINT FK_BFDFA45FAC95031');
        $this->addSql('DROP TABLE batterie_jour');
        $this->addSql('DROP TABLE consommation_jour');
        $this->addSql('DROP TABLE grille_tarifaire');
        $this->addSql('DROP TABLE import');
        $this->addSql('DROP TABLE jour');
        $this->addSql('DROP TABLE production_jour');
        $this->addSql('DROP TABLE statistique_globale');
        $this->addSql('DROP TABLE ve_jour');
    }
}
